name: intake-stac
channels:
  - conda-forge
  - informaticslab
dependencies:
  - python=3
  - geopandas
  - intake
  - intake_geopandas
  - intake-xarray
  - rasterio
  - dask
  - distributed
  - nbserverproxy
  - netcdf4
  - rasterio
  - matplotlib
  - hvplot
  - datashader
  - pip
  - pip:
    - jupyterlab
    - sat-stac
